var engines = [
  {"n":"about", "a":"", "d":"Information about yub.js", "f":"https://github.com/dohliam/yub"},
  {"n":"g", "a":"https://www.google.com/search?q=%s", "d":"Google Search", "f":"https://google.com/"},
  {"n":"gim", "a":"https://www.google.com/search?tbm=isch&q=%s", "d":"Google Image Search", "f":"https://images.google.com/"},
  {"n":"gmail", "a":"https://mail.google.com/mail/u/0/#search/%s", "d":"Gmail", "f":"https://gmail.com/"},
  {"n":"drive", "a":"https://drive.google.com/#search/%s", "d":"Google Drive", "f":"https://drive.google.com/"},
  {"n":"am", "a":"https://www.amazon.com/exec/obidos/external-search?mode=blended&keyword=%s", "d":"Amazon.com Product Search", "f":"https://www.amazon.com/"},
  {"n":"gt", "a":"https://translate.google.com/#auto/en/%s", "d":"Google Auto-Translate Text", "f":"https://translate.google.com"},
  {"n":"gtu", "a":"https://translate.google.com/translate?u=%s", "d":"Google Auto-Translate URL", "f":"https://translate.google.com"},
  {"n":"gb", "a":"https://books.google.com/books?q=%s&btnG=Search+Books", "d":"Google Books Search", "f":"https://books.google.com"},
  {"n":"gfl", "a":"https://google.com/search?q=%s&btnI=I%27m+Feeling+Lucky", "d":"Google Feeling Lucky Search", "f":"https://google.com"},
  {"n":"gm", "a":"https://maps.google.com/maps?q=%s&output=classic", "d":"Google Maps Search", "f":"https://maps.google.com"},
  {"n":"gs", "a":"https://scholar.google.com/scholar?q=%s", "d":"Google Scholar Search", "f":"https://scholar.google.com"},
  {"n":"gmt", "a":"http://www.timeanddate.com/worldclock/results.html?query=%s", "d":"Time and Date for any Location", "f":"http://timeanddate.com/worldclock"},
  {"n":"weather", "a":"http://openweathermap.org/find?q=%s", "d":"Weather from OpenWeatherMap", "f":"http://openweathermap.org/"},
  {"n":"wbm", "a":"https://web.archive.org/web/*/%s", "d":"Wayback Machine Internet Archive of URL", "f":"https://archive.org"},
  {"n":"whois", "a":"http://www.whois.sc/%s", "d":"Whois URL &amp; IP Address Listing", "f":"http://whois.sc"},
  {"n":"gwhois", "a":"https://gwhois.org/%s", "d":"GWhois DNS & IP search", "f":"https://gwhois.org"},
  {"n":"wco", "a":"https://commons.wikimedia.org/wiki/Special:Search?search=%s", "d":"Wikimedia Commons Search", "f":"https://commons.wikimedia.org/"},
  {"n":"wp", "a":"https://en.wikipedia.org/?search=%s", "d":"Wikipedia", "f":"https://en.wikipedia.org/"},
  {"n":"wv", "a":"https://en.wikivoyage.org/?search=%s", "d":"Wikivoyage", "f":"https://en.wikivoyage.org/"},
  {"n":"wt", "a":"https://en.wiktionary.org/?search=%s", "d":"Wiktionary", "f":"https://en.wiktionary.org/"},
  {"n":"wq", "a":"https://en.wikiquote.org/?search=%s", "d":"Wikiquote", "f":"https://en.wikiquote.org/"},
  {"n":"wn", "a":"https://en.wikinews.org/?search=%s", "d":"Wikinews", "f":"https://en.wikinews.org/"},
  {"n":"ws", "a":"https://en.wikisource.org/?search=%s", "d":"Wikisource", "f":"https://en.wikisource.org/"},
  {"n":"gn", "a":"https://news.google.com/news?q=%s", "d":"Google News", "f":"https://news.google.com"},
  {"n":"yt", "a":"https://www.youtube.com/results?search_type=&search_query=%s&aq=f", "d":"YouTube Video Search", "f":"https://www.youtube.com/"},
  {"n":"fcc", "a":"https://www.flickr.com/search/?q=%s&l=4", "d":"Flickr cc-by Image Search", "f":"https://www.flickr.com/creativecommons/by-2.0/"},
  {"n":"flk", "a":"https://www.flickr.com/search?text=%s", "d":"Flickr Image Search", "f":"https://www.flickr.com/"},
  {"n":"play", "a":"https://play.google.com/store/search?q=%s&c=apps&price=1", "d":"Google Play Store Search", "f":"https://play.google.com/"},
  {"n":"opc", "a":"https://openclipart.org/search/?query=%s", "d":"Open Clipart Search", "f":"https://openclipart.org/"},
  {"n":"gten", "a":"https://translate.google.com/translate_t#%s|en", "d":"Google Translate page for specified language -> English", "f":"https://translate.google.com/"},
  {"n":"cache", "a":"https://google.com/search?q=cache:%s&strip=1", "d":"Google text-only cache of a webpage", "f":"https://google.com"},
  {"n":"cat", "a":"https://google.com/search?q=cache:%s&strip=1", "d":"output webpage text from Google cache", "f":"https://google.com"},
  {"n":"yn", "a":"https://news.search.yahoo.com/search?p=%s", "d":"Yahoo News", "f":"http://news.yahoo.com/"},
  {"n":"onelook", "a":"http://www.onelook.com/?w=%s&ls=a", "d":"Onelook Dictionary Search", "f":"http://www.onelook.com/"},
  {"n":"olr", "a":"http://www.onelook.com/?w=*&loc=revfp2&clue=%s", "d":"OneLook Reverse Dictionary", "f":"http://www.onelook.com/reverse-dictionary.shtml"},
  {"n":"ud", "a":"http://www.urbandictionary.com/define.php?term=%s", "d":"Urban Dictionary Search", "f":"http://www.urbandictionary.com/"},
  {"n":"dic", "a":"http://dictionary.reference.com/browse/%s", "d":"Dictionary.com", "f":"http://dictionary.com/"},
  {"n":"thes", "a":"http://www.wordreference.com/thesaurus/%s", "d":"WordReference.com English Thesaurus", "f":"http://www.wordreference.com/thesaurus/"},
  {"n":"ted", "a":"https://www.ted.com/search?q=%s", "d":"TED Talks", "f":"https://ted.com"},
  {"n":"r", "a":"https://reddit.com/r/%s", "d":"Reddit", "f":"https://reddit.com"},
  {"n":"ddg", "a":"https://duckduckgo.com/?q=%s", "d":"DuckDuckGo Search", "f":"https://duckduckgo.com/"},
  {"n":"ext", "a":"http://filext.com/file-extension/%s", "d":"FILExt - File Extension Search", "f":"http://filext.com/"},
  {"n":"ebay", "a":"https://www.ebay.com/sch/i.html?_nkw=%s", "d":"Ebay", "f":"https://www.ebay.com/"},
  {"n":"tw", "a":"https://twitter.com/%s", "d":"Twitter", "f":"https://twitter.com/"},
  {"n":"tws", "a":"https://twitter.com/search?q=%s", "d":"Twitter Search", "f":"https://twitter.com/search-advanced"},
  {"n":"imgur", "a":"https://imgur.com/search?q=%s", "d":"Imgur - Image Sharer", "f":"https://imgur.com/"},
  {"n":"gpdf", "a":"https://www.google.com/search?q=filetype:pdf+%s", "d":"Google PDF Search", "f":"https://www.google.com/search?q=filetype:pdf"},
  {"n":"gfim", "a":"https://www.google.com/search?tbm=isch&as_q=%s&tbs=sur:fmc", "d":"Google Free Image Search", "f":"https://images.google.com/"},
  {"n":"ngram", "a":"https://books.google.com/ngrams/graph?content=%s", "d":"Google Books Ngram Viewer", "f":"https://books.google.com/ngrams"},
  {"n":"gnas", "a":"https://www.google.com/search?q=%s site:news.google.com/newspapers", "d":"Google News Archive Search", "f":"http://news.google.com/newspapers"},
  {"n":"gsite", "a":"https://www.google.com/search?q=site:%s", "d":"Google Site Search", "f":"http://google.com/"},
  {"n":"hn", "a":"https://hn.algolia.com/?q=%s", "d":"Hacker News", "f":"https://news.ycombinator.com/"},
  {"n":"how", "a":"http://www.wikihow.com/?search=%s", "d":"wikiHow - How to do anything", "f":"http://www.wikihow.com/"},
  {"n":"ifixit", "a":"https://www.ifixit.com/Guide/search/%s", "d":"iFixit - The free repair manual", "f":"http://www.ifixit.com/"},
  {"n":"y", "a":"https://search.yahoo.com/search;?p=%s", "d":"Yahoo", "f":"https://yahoo.com"},
  {"n":"yim", "a":"https://images.search.yahoo.com/search/images;?p=%s", "d":"Yahoo Image Search", "f":"https://images.search.yahoo.com/"},
  {"n":"yv", "a":"https://video.search.yahoo.com/search/video;?p=%s", "d":"Yahoo Video Search", "f":"https://video.search.yahoo.com/"},
  {"n":"ym", "a":"https://maps.yahoo.com/place/?addr=%s", "d":"Yahoo Maps", "f":"https://maps.yahoo.com"},
  {"n":"b", "a":"https://www.bing.com/search?q=%s", "d":"Bing Search", "f":"https://www.bing.com/"},
  {"n":"bim", "a":"https://www.bing.com/images/search?q=%s", "d":"Bing Image Search", "f":"https://www.bing.com/images/"},
  {"n":"btr", "a":"", "d":"Bing Translator", "f":"https://www.bing.com/translator/"},
  {"n":"bn", "a":"https://www.bing.com/news/search?q=%s", "d":"Bing News", "f":"https://www.bing.com/news/"},
  {"n":"bm", "a":"https://www.bing.com/maps/?where1=%s", "d":"Bing Maps", "f":"https://www.bing.com/maps/"},
  {"n":"bv", "a":"https://www.bing.com/videos/search?q=%s", "d":"Bing Videos", "f":"https://www.bing.com/videos/"},
  {"n":"gut", "a":"https://www.gutenberg.org/ebooks/search/?query=%s", "d":"Project Gutenberg", "f":"https://www.gutenberg.org/"},
  {"n":"forvo", "a":"http://www.forvo.com/word/%s", "d":"Forvo Pronunciations", "f":"http://www.forvo.com/"},
  {"n":"gc", "a":"https://code.google.com/hosting/search?q=%s", "d":"Google Code", "f":"https://code.google.com/"},
  {"n":"sf", "a":"https://sourceforge.net/directory?q=%s", "d":"SourceForge", "f":"https://sourceforge.net/"},
  {"n":"git", "a":"https://github.com/search?q=%s", "d":"GitHub", "f":"https://github.com/"},
  {"n":"bbc", "a":"http://www.bbc.co.uk/search?q=%s", "d":"BBC News", "f":"http://www.bbc.com/news/"},
  {"n":"dw", "a":"http://www.dw.de/search/english/%s/category/9097/", "d":"Deutsche Welle - English (English)", "f":"http://www.dw.de/"},
  {"n":"nhken", "a":"http://www2.nhk.or.jp/nhkworld/search/query.cgi?qt=%s", "d":"NHK World - English", "f":"http://www3.nhk.or.jp/nhkworld/"},
  {"n":"fr24en", "a":"http://www.france24.com/en/search/?Search[term]=%s&Search[page]=1", "d":"France 24 (en) - International News 24/7", "f":"http://www.france24.com/en/"},
  {"n":"rfien", "a":"http://www.english.rfi.fr/search/sinequa_search/%s", "d":"RFI (en)", "f":"http://www.english.rfi.fr/"},
  {"n":"abc", "a":"http://www.radioaustralia.net.au/international/search/%s", "d":"ABC Radio Australia", "f":"http://www.radioaustralia.net.au/"},
  {"n":"gg", "a":"https://groups.google.com/forum/#!search/%s", "d":"Google Groups", "f":"https://groups.google.com/"},
  {"n":"yg", "a":"https://groups.yahoo.com/neo/search?query=%s", "d":"Yahoo Groups", "f":"https://groups.yahoo.com/"},
  {"n":"so", "a":"https://stackoverflow.com/search?q=%s", "d":"Stack Overflow", "f":"https://stackoverflow.com/"},
  {"n":"yw", "a":"", "d":"Yahoo Weather", "f":"https://weather.yahoo.com/"},
  {"n":"yelp", "a":"http://www.yelp.com/search?find_desc=%s", "d":"Yelp", "f":"http://www.yelp.com/"},
  {"n":"cnn", "a":"http://edition.cnn.com/search/?query=%s", "d":"CNN International", "f":"http://edition.cnn.com/"},
  {"n":"rci", "a":"http://www.rcinet.ca/en/?s=%s", "d":"Radio Canada International - English", "f":"http://www.rcinet.ca/en/"},
  {"n":"cbc", "a":"http://www.cbc.ca/gsa/?q=%s", "d":"CBC News - Canadian Broadcasting Corporation", "f":"http://www.cbc.ca/news"},
  {"n":"db", "a":"https://www.dropbox.com/home/%s", "d":"Dropbox", "f":"https://dropbox.com"},
  {"n":"ibn", "a":"http://ibnlive.in.com/searcher/search.php?searchq=%s", "d":"CNN-IBN News - Indian Broadcasting Network (English)", "f":"http://ibnlive.in.com/"},
  {"n":"voa", "a":"http://www.voanews.com/search/search2.aspx#all|%s|0|allzones|min|now", "d":"Voice of America News (English)", "f":"http://www.voanews.com/"},
  {"n":"rpen", "a":"http://radio.cz/en/search/?query=%s", "d":"Radio Prague (en)", "f":"http://radio.cz/en"},
  {"n":"xhen", "a":"http://search.news.cn/language/search.jspa?id=en&t=1&t1=0&ss=&ct=&n1=%s&button=ok", "d":"Xinhua English (en)", "f":"http://www.news.cn/english/"},
  {"n":"ymail", "a":"", "d":"Yahoo Mail", "f":"https://mail.yahoo.com"},
  {"n":"mail", "a":"", "d":"Mail.com", "f":"https://www.mail.com/"},
  {"n":"hmail", "a":"", "d":"Hotmail", "f":"https://hotmail.com"},
  {"n":"omail", "a":"", "d":"Outlook.com E-mail", "f":"https://outlook.com"},
  {"n":"dd", "a":"https://downdetector.com/search/?q=%s", "d":"Down Detector", "f":"https://downdetector.com/"},
  {"n":"isup", "a":"http://www.downforeveryoneorjustme.com/%s", "d":"Down For Everyone Or Just Me", "f":"http://www.downforeveryoneorjustme.com/"},
  {"n":"dfeojm", "a":"http://www.downforeveryoneorjustme.com/%s", "d":"Down For Everyone Or Just Me", "f":"http://www.downforeveryoneorjustme.com/"},
  {"n":"ip", "a":"", "d":"What Is My IP", "f":"http://www.whatismyip.com/"},
  {"n":"ggv", "a":"https://www.google.com/search?tbm=vid&q=%s", "d":"Google Video Search", "f":"https://video.google.com/"},
  {"n":"gflights", "a":"https://www.google.ca/flights/#search;t=%s", "d":"Google Flights Search", "f":"https://flights.google.com/"},
  {"n":"trends", "a":"https://www.google.ca/trends/explore#q=%s", "d":"Google Trends", "f":"https://www.google.com/trends/"},
  {"n":"sp", "a":"https://startpage.com/do/search?query=%s", "d":"Startpage Web Search", "f":"https://startpage.com/"},
  {"n":"spim", "a":"https://startpage.com/do/search?cat=pics&query=%s", "d":"Startpage Image Search", "f":"https://startpage.com/"},
  {"n":"spv", "a":"https://startpage.com/do/search?cat=video&query=%s", "d":"Startpage Video Search", "f":"https://startpage.com/"},
  {"n":"spsite", "a":"https://startpage.com/do/search?query=site:%s", "d":"Startpage Site Search", "f":"https://startpage.com/"},
  {"n":"ix", "a":"https://ixquick.com/do/search?q=%s", "d":"Ixquick Search Engine", "f":"https://www.ixquick.com/"},
  {"n":"ixim", "a":"https://ixquick.com/do/search?cat=pics&query=%s", "d":"Ixquick Image Search", "f":"https://ixquick.com/"},
  {"n":"ixv", "a":"https://ixquick.com/do/search?cat=video&query=%s", "d":"Ixquick Video Search", "f":"https://ixquick.com/"},
  {"n":"ixsite", "a":"https://ixquick.com/do/search?q=site:%s", "d":"Ixquick Site Search", "f":"https://www.ixquick.com/"},
  {"n":"blv", "a":"http://www.blinkx.com/search/%s", "d":"Blinkx Video Search", "f":"http://www.blinkx.com/"},
  {"n":"vi", "a":"http://vimeo.com/search?q=%s", "d":"Vimeo Videos", "f":"https://vimeo.com/"},
  {"n":"fspam", "a":"http://www.stopforumspam.com/ipcheck/%s", "d":"Stop Forum Spam - IP Check", "f":"http://www.stopforumspam.com/"},
  {"n":"lmd", "a":"http://mondediplo.com/spip.php?page=recherche&recherche=%s", "d":"Le Monde diplomatique - English edition", "f":"http://mondediplo.com/"},
  {"n":"gv", "a":"http://globalvoicesonline.org/?s=%s", "d":"Global Voices (en)", "f":"http://globalvoicesonline.org/"},
  {"n":"eun", "a":"", "d":"Euronews (en)", "f":"http://www.euronews.com/"},
  {"n":"reu", "a":"http://www.reuters.com/search?blob=%s", "d":"Reuters", "f":"http://www.reuters.com/"},
  {"n":"swi", "a":"http://www.swissinfo.ch/action/eng/40468904/search?query=%s", "d":"SwissInfo (en)", "f":"http://www.swissinfo.ch/eng"},
  {"n":"rt", "a":"http://rt.com/search/everywhere/term/%s/", "d":"RT - Russia Today (en)", "f":"http://rt.com/"},
  {"n":"blm", "a":"http://search1.bloomberg.com/search/?content_type=all&q=%s", "d":"Bloomberg News", "f":"http://www.bloomberg.com/news/"},
  {"n":"ascii", "a":"http://www.network-science.de/ascii/ascii.php?TEXT=%s&x=8&y=7&FONT=_all+fonts+with+your+text_&RICH=no&FORM=left&STRE=no", "d":"ASCII Generator", "f":"http://www.network-science.de/ascii/"},
  {"n":"del", "a":"https://delicious.com/tag/%s", "d":"Delicious.com tag search", "f":"https://delicious.com/"},
  {"n":"cisi", "a":"http://www.canistream.it/search/movie/infernal", "d":"Can I Stream It? - Movie Search", "f":"http://www.canistream.it/"},
  {"n":"wa", "a":"https://www.wolframalpha.com/input/?i=%s", "d":"Wolfram Alpha", "f":"https://www.wolframalpha.com/"},
  {"n":"npr", "a":"http://www.npr.org/templates/search/index.php?searchinput=%s", "d":"NPR - National Public Radio", "f":"http://www.npr.org/"},
  {"n":"fspell", "a":"http://metaatem.net/words/%s", "d":"Spell with flickr", "f":"http://metaatem.net/words/"},
  {"n":"mo", "a":"https://www.google.com/gwt/n?u=%s", "d":"Show mobile version of page (via Google)", "f":"https://www.google.com/"},
  {"n":"js", "a":"https://developer.mozilla.org/en-US/search?q=%s", "d":"Search JavaScript documentation", "f":"https://developer.mozilla.org/en-US/docs/Web/JavaScript"},
  {"n":"rb", "a":"http://ruby-doc.com/search.html?q=%s", "d":"Search Ruby documentation", "f":"http://ruby-doc.com/"},
  {"n":"php", "a":"https://www.php.net/%s", "d":"Search PHP documentation", "f":"http://www.php.net/"},
  {"n":"py", "a":"https://docs.python.org/3/search.html?q=%s", "d":"Search Python documentation", "f":"https://docs.python.org/"},
  {"n":"sh", "a":"http://mywiki.wooledge.org/ParsingLs?action=fullsearch&context=180&value=%s&fullsearch=Text", "d":"Search Bash documentation on BashFAQ", "f":"http://mywiki.wooledge.org/BashFAQ/"},
  {"n":"jshint", "a":"", "d":"JSHint, a JavaScript Code Quality Tool", "f":"http://jshint.com/"},
  {"n":"flint", "a":"https://www.flickr.com/photos/tags/%s/interesting/", "d":"Search Flickr for images, sorted by \"interestingness\"", "f":"https://www.flickr.com/"},
  {"n":"lman", "a":"http://man.he.net/?section=all&topic=%s", "d":"Linux Man Pages Online", "f":"http://man.he.net/"},
  {"n":"hl", "a":"http://news.search.yahoo.com/news/rss?ei=UTF-8&p=%s&c=&eo=UTF-8", "d":"Show a list of Yahoo News headlines on a particular topic", "f":"http://news.search.yahoo.com/"},
  {"n":"imdb", "a":"http://www.imdb.com/find?q=%s", "d":"IMDB - International Movie Database", "f":"http://www.imdb.com/"},
  {"n":"ccm", "a":"http://ccmixter.org/api/query?search=%s", "d":"ccMixter", "f":"http://ccmixter.org/"},
  {"n":"ccmt", "a":"http://ccmixter.org/api/query?tags=%s", "d":"ccMixter Tag Search", "f":"http://ccmixter.org/"},
  {"n":"jam", "a":"https://www.jamendo.com/en/search?qs=q=%s", "d":"Jamendo - Royalty Free Music", "f":"https://www.jamendo.com/"},
  {"n":"sc", "a":"https://soundcloud.com/search?q=%s", "d":"SoundCloud", "f":"https://soundcloud.com/"},
  {"n":"ar", "a":"https://archive.org/search.php?query=%s", "d":"Internet Archive", "f":"https://archive.org/"},
  {"n":"medium", "a":"https://medium.com/search?q=%s", "d":"Medium Search", "f":"https://medium.com/"}
];
